---
# Install needed repos and apps for MY Fedora Workstation
- hosts: localhost
  become: yes
  tasks:
  - name: Install RPM Fusion repos
    yum:
      name: ['https://download1.rpmfusion.org/free/el/rpmfusion-free-release-7.noarch.rpm, https://download1.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-7.noarch.rpm']
      state: present

  - name: Install Chrome repo
    copy: 
      src: google-chrome.repo
      dest: /etc/yum.repos.d/

  - name: Import Google Chrome signing key
    rpm_key:
      key: https://dl-ssl.google.com/linux/linux_signing_key.pub
      state: present 

  - name: Install MS Visual Code repo
    copy: 
      src: vscode.repo
      dest: /etc/yum.repos.d/

  - name: Import VS Code signing key
    rpm_key:
      key: https://packages.microsoft.com/keys/microsoft.asc
      state: present

  - name: Add Flatpak repo
    flatpak_remote:
      name: flathub
      state: present
      flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

  - name: Install a bunch of apps from misc repos with yum
    yum:
      name: ['nano', 'htop', 'google-chrome-stable', 'code', 'remmina', 'snap']
      state: present

  - name: Install Flatpak apps
    flatpak:
      name: "{{ item }}"
      state: present
    with_items:
      - com.bluejeans.BlueJeans
      - com.spotify.Client
      - com.valvesoftware.Steam

  - name: Install Snap app Tusk aka Evernote
    command: snap install tusk --classic
